logging:
  level:
    root: INFO
    com.auto.trader: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF         # 바인딩 로그
    org.hibernate.orm.jdbc.extract: OFF      # 결과 추출 로그
    org.hibernate.sql.results.internal: OFF  # 결과 매핑 로그
    org.hibernate.type.descriptor.sql: OFF
    org.hibernate.stat: OFF

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/FinanceHelper
    username: auto_trader
    password: Wpguq1986!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

server:
  servlet:
    session:
      cookie:
        same-site: none
        secure: true
